/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DiagnoseRouteImport } from './routes/diagnose'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultIdRouteImport } from './routes/result.$id'

const DiagnoseRoute = DiagnoseRouteImport.update({
  id: '/diagnose',
  path: '/diagnose',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultIdRoute = ResultIdRouteImport.update({
  id: '/result/$id',
  path: '/result/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/callback': typeof CallbackRoute
  '/diagnose': typeof DiagnoseRoute
  '/result/$id': typeof ResultIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/callback': typeof CallbackRoute
  '/diagnose': typeof DiagnoseRoute
  '/result/$id': typeof ResultIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/callback': typeof CallbackRoute
  '/diagnose': typeof DiagnoseRoute
  '/result/$id': typeof ResultIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/callback' | '/diagnose' | '/result/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/callback' | '/diagnose' | '/result/$id'
  id: '__root__' | '/' | '/auth' | '/callback' | '/diagnose' | '/result/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CallbackRoute: typeof CallbackRoute
  DiagnoseRoute: typeof DiagnoseRoute
  ResultIdRoute: typeof ResultIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/diagnose': {
      id: '/diagnose'
      path: '/diagnose'
      fullPath: '/diagnose'
      preLoaderRoute: typeof DiagnoseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/$id': {
      id: '/result/$id'
      path: '/result/$id'
      fullPath: '/result/$id'
      preLoaderRoute: typeof ResultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CallbackRoute: CallbackRoute,
  DiagnoseRoute: DiagnoseRoute,
  ResultIdRoute: ResultIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
